package com.g93.be.chat;

public enum BusinessQueryIntent {
    TODAY_EXAMINATION_COUNT,
    TODAY_EXAMINATION_LIST,
    EXAMINATION_LIST,
    EXAMINATION_COUNT,
    REPORT_COUNT,
    EXAMINATION_FINAL_RESULT,
    REPORT_SUMMARY,
    GRADE_DISTRIBUTION,
    GRADE_COUNT,
    UNKNOWN
}
