name: capstone

services:
  mysql:
    image: dhi.io/mysql:9
    container_name: capstone-mysql
    restart: unless-stopped
    env_file:
      - ../env/database.env
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 -uroot -p$$MYSQL_ROOT_PASSWORD --silent",
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

  maildev:
    image: maildev/maildev:2.1.0
    container_name: capstone-maildev
    restart: unless-stopped
    ports:
      - "1080:1080" # Web UI
      - "1025:1025" # SMTP Port

  redis:
    image: dhi.io/redis:8-alpine
    container_name: capstone-redis
    restart: unless-stopped
    # env_file:
    #   - ../env/redis.env
    ports:
      - "6379:6379"
    command: redis-server --protected-mode no

  be:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: capstone-be
    restart: unless-stopped
    ports:
      - "8000:8080"
    env_file:
      - ../env/be.env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ./data:/app/data

  ai:
    build:
      context: ../mkaix.healthsynml
      dockerfile: Dockerfile
    container_name: capstone-ai
    restart: unless-stopped
    ports:
      - "8005:8005"
    volumes:
      - ../mkaix.healthsynml/checkpoints:/app/checkpoints

volumes:
  mysql_data:
