# yaml-language-server: $schema=none
server:
  servlet:
    context-path: /api/v1
  forward-headers-strategy: framework

spring:
  application:
    name: be
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 500MB
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:capstone}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC&nullCatalogMeansCurrent=true
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:capstone_root_password}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    properties:
      hibernate:
        default_catalog: ${DB_NAME:capstone}
        default_schema: ${DB_NAME:capstone}
        format_sql: true

  data:
    redis:
      client-type: jedis
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

  mail:
    host: ${SPRING_MAIL_HOST:localhost}
    port: ${SPRING_MAIL_PORT:1025}
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  jwt:
    issuer: capstone-ai-knee-diagnosis
    access-secret: ${JWT_ACCESS_SECRET:dGVzdC1hY2Nlc3Mtc2VjcmV0LWtleS1tdXN0LWJlLWF0LWxlYXN0LTI1Ni1iaXRzLWxvbmc=}
    refresh-secret: ${JWT_REFRESH_SECRET:dGVzdC1yZWZyZXNoLXNlY3JldC1rZXktbXVzdC1iZS1hdC1sZWFzdC0yNTYtYml0cy1sb25n}
    access-expiration-ms: 900000 # 15 minutes
    refresh-expiration-ms: 604800000 # 7 days
  aws:
    region: ${AWS_REGION:ap-southeast-1}
    s3:
      bucket: ${AWS_BUCKET_NAME:test-bucket-819109476069-ap-southeast-1-an}
  storage:
    base-dir: ${APP_STORAGE_BASE_DIR:D:/Capstone/data}
  avatar:
    storage-dir: ${APP_AVATAR_STORAGE_DIR:${app.storage.base-dir}/avatars}
  pdf:
    export-dir: ${APP_PDF_EXPORT_DIR:${app.storage.base-dir}/reports}
  ai:
    api-url: ${APP_AI_API_URL:http://localhost:8005/api/v1/predict}

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsManagerConfigurer: ERROR
