spring:
  datasource:
    url: jdbc:mysql://localhost:3306/capstone?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

  data:
    redis:
      client-type: jedis
      host: localhost
      port: 6379

  mail:
    host: localhost
    port: 1025
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

app:
  aws:
    region: ${AWS_REGION:ap-southeast-1}
    s3:
      bucket: ${AWS_BUCKET_NAME:test-bucket-819109476069-ap-southeast-1-an}
  storage:
    base-dir: ${APP_STORAGE_BASE_DIR:D:/Capstone/data}
  ai:
    api-url: http://54.254.113.71:8005/api/v1/predict
