Project capstone_ai_knee_xray_diagnosis {
  database_type: "MySQL"
  note: "Database schema based on new ERD"
}

Table roles {
  id bigint [pk, increment]
  name varchar(50)
}

Table features {
  id bigint [pk, increment]
  name varchar(100)
}

Table permissions {
  id bigint [pk, increment]
  name varchar(100)
  feature_id bigint
  role_id bigint
}

Table users {
  id bigint [pk, increment]
  email varchar(150)
  username varchar(50)
  password varchar(100)
  phone varchar(30)
  full_name varchar(150)
  dob date
  user_type varchar(50)
  avatar_image_id bigint
  status varchar(50)
  gender varchar(20)
  create_at datetime
  update_at datetime
  role_id bigint
}

Table admins {
  id bigint [pk]
}

Table doctors {
  id bigint [pk]
  years_of_experience int
}

Table notifications {
  id bigint [pk, increment]
  user_id bigint
  title varchar(150)
  message text
  type varchar(50)
  is_read boolean
  create_at datetime
  read_at datetime
}

Table audit_logs {
  id bigint [pk, increment]
  user_id bigint
  title varchar(150)
  description text
  ip_address varchar(100)
  user_agent varchar(255)
  time_stamp datetime
}

Table images {
  id bigint [pk, increment]
  extension varchar(10)
  s3_bucket_id varchar(255)
  s3_bucket_key varchar(255)
}

Table patients {
  id bigint [pk, increment]
}

Table examinations {
  id bigint [pk, increment]
  patient_id bigint
  doctor_id bigint
  encounter_code varchar(100)
  visit_time datetime
  status varchar(50)
  chief_complaint text
  clinical_notes text
  priority varchar(50)
  created_at datetime
  final_diagnosis text
}

Table dicom_instances {
  id bigint [pk, increment]
  study_date datetime
  study_description varchar(255)
  modality varchar(50)
  study_instance_uid varchar(150)
  series_instance_uid varchar(150)
  instance_uid varchar(150)
  seri_id varchar(150)
  created_at datetime
  dicom_image_id bigint
  png_image_id bigint
  examination_id bigint
}

Table ai_analyses {
  id bigint [pk, increment]
  examination_id bigint
  start_date datetime
  duration int
  status varchar(50)
  token varchar(255)
  average_level varchar(50)
  final_diagnosis text
  number_of_result int
  accuracy_rate decimal(5,4)
  created_at datetime
}

Table result_attachments {
  id bigint [pk, increment]
  dicom_study_id bigint
  KL_level varchar(50)
  diagnosis text
  accuracy_rate decimal(5,4)
}

Ref: permissions.feature_id > features.id
Ref: permissions.role_id > roles.id
Ref: users.role_id > roles.id
Ref: users.avatar_image_id > images.id
Ref: admins.id - users.id
Ref: doctors.id - users.id
Ref: notifications.user_id > users.id
Ref: audit_logs.user_id > users.id
Ref: examinations.patient_id > patients.id
Ref: examinations.doctor_id > doctors.id
Ref: dicom_instances.examination_id > examinations.id
Ref: dicom_instances.dicom_image_id > images.id
Ref: dicom_instances.png_image_id > images.id
Ref: ai_analyses.examination_id > examinations.id
Ref: result_attachments.dicom_study_id > dicom_instances.id
